MODEL:
  WEIGHT: ""
  TRANSFER_LEARNING: False
  COMMON:
    GAN_TYPE: 'lsgan'
    TRAINING_RATE: 1
    WEIGHT_ADV_G: 300.0
    WEIGHT_ADV_D: 300.0
    WEIGHT_G_CON: 1.5
    WEIGHT_G_STYLE: 2.5
    WEIGHT_G_COLOR: 10.0
    WEIGHT_G_TV: 1.0
    WEIGHT_D_LOSS_REAL: 1.7
    WEIGHT_D_LOSS_FAKE: 1.7
    WEIGHT_D_LOSS_GRAY: 1.7
    WEIGHT_D_LOSS_BLUR: 1.0
  BACKBONE:
    BODY: "VGG19"
  GENERATOR:
    BODY: "Base-256"
    IN_CHANNELS: 3
  DISCRIMINATOR:
    BODY: "Base-256"
    IN_CHANNELS: 3
    N_DIS: 2
DATASETS:
  TRAIN: [
    {
      'factory': 'AnimeGanDataset',
      'dataDir': '/data/datasets/animegan/Shinkai',
      'split': 'train'
    }
  ]
  TEST: [
    {
      'factory': 'AnimeGanDataset',
      'dataDir': '/data/datasets/animegan/Shinkai',
      'split': 'test'
    }
  ]
INPUT:
  IMG_SIZE: (256, 256)
  PIXEL_MEAN: [-4.4661, -8.6698, 13.1360]
DATALOADER:
  NUM_WORKERS: 1
SOLVER:
  MAX_EPOCH: 100
  PRINT_PERIOD: 20
  CHECKPOINT_PERIOD: 20
  TEST_PERIOD: 1
  IMS_PER_BATCH: 8
  GENERATOR:
    BASE_LR: 0.0002
    INIT_EPOCH: 10
    STEPS: (10,)
    WARMUP_FACTOR: 0.0
    WARMUP_ITERS: 0
    WARMUP_METHOD: 'constant'
  DISCRIMINATOR:
    BASE_LR: 0.00004
    STEPS: (100,)
    WARMUP_FACTOR: 0.0
    WARMUP_ITERS: 0
    WARMUP_METHOD: 'constant'
TEST:
  IMS_PER_BATCH: 8